version = 0.1

[default]
[default.global.parameters]
stack_name = "expense-tracker-aws"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "expense-tracker-aws"
region = "us-east-1"
parameter_overrides = "Environment=\"dev\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev]
[dev.deploy.parameters]
stack_name = "expense-tracker-aws-dev"
parameter_overrides = "Environment=\"dev\""
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[staging]
[staging.deploy.parameters]
stack_name = "expense-tracker-aws-staging"
parameter_overrides = "Environment=\"staging\""
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[prod]
[prod.deploy.parameters]
stack_name = "expense-tracker-aws-prod"
parameter_overrides = "Environment=\"prod\""
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
